server:
  error:
    include-message: always
  port: 8080

spring:
  application:
    name: rsql_example
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DATABASE:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

rsql:
  defaultSort: ${DEFAULT_SORT:createdAt,asc}
  defaultPageSize: ${DEFAULT_PAGE_SIZE:10}
